datalad/datalad-gooey

- datalad_gooey/app.py
- datalad_gooey/dataladcmd_exec.py
Turn exceptions bubbling up from datalad command calls into a signal
(currently being picked up by status bar). Otherwise gooey fails to give
any indication of failure in such case, since the exception is in a
different thread.
> Add exception handling to command execution

- datalad_gooey/dataladcmd_exec.py
With this, `path` arguments should be resolved against the dataset
rather than the CWD of the GUI process.
Closes #24
> Pass dataset as object, not str to datalad commands

- .gitignore
- datalad_gooey/app.py
- datalad_gooey/gooey.py
- datalad_gooey/resources/icons/app_icon_32.svg
This PR aims to address #40 in part. It:
- adds an SVG icon image, white background, rounded corners, 32x32 px
- adds a wrapper around `QtApplication` such that the code can be grouped with the new lines that add the icon and such that the same code can be called from multiple entrypoints.
- updates `.gitignore` for Mac developers
Next steps / help needed:
- this looks okay on a Mac (see snapshot below) but needs some visual testing on other operating systems
- the size needs to be adjusted and I am not sure if/how this can be done parameters to the `QIcon` class, or if it requires a complete set of different icon sizes (i.e. multiple files), or via another method?
> NF: application icon functionality

- datalad_gooey/dataset_actions.py
The dataset method menu shows submenu items corresponding to dataset method groups in an unintuitive order - not whats most useful is at the top, but the group who the first command in an alphabetically sorted list belongs to.  From a UX standpoint, the first group should be the most essential commands. A sensible order of command groups already exists in the menu_lookup, but this order is lost during menu assembly, as the assembly proceeds by alphabetical order of command names (see #34). This change preserves the original order (by adding the submenues in the order they are supposed to be).
Closes #34
> Insert command group submenues unconditionally, but in right order

- datalad_gooey/fsbrowser.py
This unfreezes the UI as intended, but also puts a lot of strain on the signal/slot mechanism.
Closes datalad/datalad-gooey#59
> Implement tree widget population via a background `tree` process

- datalad_gooey/fsbrowser.py
- datalad_gooey/fsbrowser_item.py
- datalad_gooey/resources/icons/clean.svg
- datalad_gooey/resources/icons/dataset-closed.svg
- datalad_gooey/resources/icons/directory-closed.svg
- datalad_gooey/resources/icons/file-annex.svg
- datalad_gooey/resources/icons/file-git.svg
- datalad_gooey/resources/icons/file.svg
- datalad_gooey/resources/icons/modified.svg
- datalad_gooey/resources/icons/untracked.svg
This is a PR that currently:
- adds 8 SVG icons:
- one per item type: dataset, directory, file
- one per state: clean, untracked, modified
- one per storage system: git, annex
- displays the appropriate icon per item in the `Name` column, for dataset and directory:
- annotates file storage system based on the result of the `status` call, which now has the added `annex='basic'` flag
TO DO:
**Note:** The TO DO items are likely dependent on #43 and the time it takes to do `datalad status` calls...
> Adds icons and annotate item types, states and availability

- datalad_gooey/fsbrowser.py
This prevents subdatasets from being inspected for untracked content (even when the respective directories are not yet expanded).
Effectively, a subdataset annotation (attached to the root directory of a subdataset within a superdataset) now reflects whether the state of the subdataset recorded _within_ the superdataset matches the subdatasets checked-out state, or not.
> Speed-up status annotation (massively) by limiting to subds commits

- datalad_gooey/app.py
- datalad_gooey/dataladcmd_exec.py
- datalad_gooey/fsbrowser.py
This is a compound change, comprised of the following components
- `results_received` is not Signal(Interface, list): Instead of a single
results, there is no always a list of them reported, and the Interface
class of the underlying command execution is reported as an indentifier
to associate result to. The latter is done, because it is not possible
to connect slots on a per execution basis (see next change), and cheap
identification must be supported.
- Discontinue on-demand connection (disconnection) of slots. This was
never working as intended and also caused slowdown, because
connections are not unique, i.e., a particular connection could be
(and was made) multiple times, causing a signal to pass to the same
slot multiple times.
- `GooeyDataladCmdExec` now supports timed result …
> Upgrade command result signaling

- datalad_gooey/__init__.py
- datalad_gooey/app.py
- datalad_gooey/dataladcmd_exec.py
- datalad_gooey/fsbrowser.py
- datalad_gooey/fsbrowser_item.py
- datalad_gooey/lsdir.py
- datalad_gooey/status_light.py
- docs/source/index.rst
The current implementation based on `datalad tree` is flawed, because it cannot list deleted content (which is likely needed, or a source of confusion in the context of a version control system).
This changeset provides a custom helper for Gooey to perform the required exploration (list the content of a single directory, non-recursively), with type information on all children.
`datalad gooey-lsdir` provides this functionality. it is implemented as a thin wrapper around `git ls-files`, reusing some helpers from datalad-core (which could be better tuned for this purpose).
It is faster than the current `tree`-based implementation, and tons faster than a possible alternative switch to `datalad status`.
The following stats are for listing a directory with 36k annexed files
```
timeit …
```
> Custom tree exploration helper

- datalad_gooey/dataladcmd_exec.py
There are two Signals triggering a datalad command execution: `configure_dataladcmd` and `execute_dataladcmd`. Definition of the former did not match the latter resulting in `GooeyDataladCmdUI` emmitting a signal that the receiver did not properly handle, b/c it got a `None` where it expects a `dict` leading to an "invisible" `AttributeError`.
Closes #84
There are related questions, though, @mih :
- It appears that the `configure_dataladcmd` is defined twice - in app and `GooeyDataladCmdUI`. Looks to me as if the former isn't used (emitted) anywhere. Is that right and should it therefore be deleted?
- Alternatively to the proposed solution, `_cmdexec_thread` and/or the `execute` slot could get an empty dict as default value. I went for this, because we may want to introduce some command …
> Unify command execution Signals

- datalad_gooey/app.py
Fixes #95 by excepting an Error that is thrown when a installed development version of DataLad is more recent than the most recent release
> Guard datalad version check against refusing the future

- datalad_gooey/gooey.py
Might be a fix for #97. This is how it looks when no path is given to the gooey command:
The dialog is skipped when a path is provided, and an empty path is passed if the user cancels the directory picking.
> Add a directory picker before App startup if no path is specified

- datalad_gooey/app.py
If you consider  #103 a bug, this PR is the fix. It time-outs the Finished... message of successfully ran commands after one second.
Fixes #103
> Add a timeout of 1sec to status bar's 'Finished...' message

- datalad_gooey/fsbrowser.py
This change makes the file tree view expand (and shrink the type and state sections to gain space) to display longer filepaths or file paths in freshly opened subdirectories.
Looks like this:
> Make Filetree width adjust itself to path length

- datalad_gooey/app.py
The rational is that the logviewer is how datalad commands communicate information to the user. The update check is running modal (blocking) in the foreground, and using a dialog matches that mode of operation.
> Use a dialog to report on version check

- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/param_form_utils.py
This addresses the comment by @adswa made in
https://github.com/datalad/datalad-gooey/issues/106#issuecomment-1250737738
> Make Path selctor basedir use app root path, unless dataset given

- datalad_gooey/app.py
- datalad_gooey/dataladcmd_exec.py
Whenever a command execution starts, a tool button is shown in the status bar. When clicked that button causes a stop flag to be set in the `GooeyDataladCmdExec`, which causes the execution thread to raise an `InterruptedError` exception when it receives the next command result.
All gather results (up to this point) are captured and emitted. The resulting code path is the same as if the command had crashed on its own.
On exit (forced or natural), the kill button is hidding again.
Right now the implementation can only deal with a single running thread, so it needs to be adjusted, whenever we start supporting more than one.
We likely need to support requesting a manual re-exploration of directories in the file browser now, because user can (and will) interrupt the initial traversal and …
> Simplistic approach to stop a command execution thread

- datalad_gooey/__init__.py
- datalad_gooey/app.py
- datalad_gooey/gooey.py
- datalad_gooey/resources/ui/main_window.ui
- setup.cfg
Offer 'system' (no change), and a 'light', and 'dark' theme.
Configurable via menu and `datalad.gooey.ui-theme` config switch.
Closes #133
> Basic UI themeing support

- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/param_multival_widget.py
- datalad_gooey/param_widgets.py
- datalad_gooey/tests/test_param_widget.py
This changeset contains a range of significant updates
- Pre-setting a parameter value no longer disables the input widget. It merely sets the initial value.
- Parameter widgets (should) now emit a `value_changed` signal, whenever the value they would return on `get_gooey_param_spec()` would change.
- Parameter widget can now receive updates to other parameters via a init_gooey_from_other_param() slot. The default implementation does nothing, but particular widgets can use this to implement dynamic reconfiguration (set a new basedir for a filedialog when the reference dataset changes, etc)
- Parameters provide the `emit_gooey_value_changed()` method that can be used to connect "changed" signals of underlying input widget to, in order to emit standard `value_changed` signals with an …
> Dynamic command parameter input form

- .appveyor.yml
- .github/workflows/test_crippledfs.yml
- datalad_gooey/tests/test_dataladcmd_exec.py
- requirements-devel.txt
This introduces the use of `pytest-qt` (and `xvfb` + `pytest-xvfb` for the CI runs) and enhances the test for command execution with it.
While everything looks fine that way, I am actually not quite sure how it manages to run with the CI builds on windows and mac. However, the logs show that the test in question is clearly executed and passes.
Addressing #48
> Introduce signal testing

- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
Long tracebacks can completely fill the log/console tab, obscuring the command logs and custom rendering (see #141).
This change sends tracebacks to a dedicated 'traceback' tab.
> Send Tracebacks to dedicated Traceback tab to prevent clutter

- datalad_gooey/api_utils.py
- datalad_gooey/complete_api.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/param_multival_widget.py
- datalad_gooey/param_widgets.py
- datalad_gooey/utils.py
With the exception of the `dataset` argument, which is always sorted first.
> Define parameter order in "complete" API based on command signature

- datalad_gooey/app.py
Use `<pre>` to use the preformatted traceback view provided by `CapturedException.format_standard` rather than "swallowing" newlines and indentations.
> Format Traceback View

- datalad_gooey/app.py
It tried out the dark theme, and wanted to follow the warnings advice of installing the 'missing qdarktheme installation'. However, pip install qdarktheme does not find a matching package, and I didn't find a different package manager that contained a package of this name. I suppose that the relevant Python package is called pyqtdarktheme, and I think its easier to find this out if the warning uses its package name
> UX: Use Python package name of dark theme dependency

- datalad_gooey/app.py
This makes any command run in the root that is visible in the app, rather than some inaccessible (likely not useful) working directory.
Now one could run a plain `create()` and not get an wholly unexpected result.
Closes datalad/datalad-gooey#168
Moreover, any relative path is not relative to the root item in the treeview. Which is better than relative-to-who-knows.
Ping datalad/datalad-gooey#106
This change paves the way to an implementation of a fix for datalad/datalad-gooey#130
> Make GooeyApp set PWD to match its root path

- datalad_gooey/fsbrowser.py
- datalad_gooey/fsbrowser_item.py
- datalad_gooey/simplified_api.py
It makes sense to visually distinguish annexed files from files in Git. Here this is done via a dedicated type label `annexed-file`.
This logical separation enables supporting `annexed_file_api` actions for any such files, and only those.
So annexed files offer `get/drop`, but files in Git not.
Closes datalad/datalad-gooey#188
> Recognize annexed-files in browser, support dedicated actions

- datalad_gooey/constraints.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/simplified_api.py
It is now used for the `path` parameters of `clone` and `create`.
This implies that users can not longer specific non-existing locations as targets for these operations. However, this ability has already been reported as confusing: https://github.com/datalad/datalad-gooey/issues/144
Closes datalad/datalad-gooey#153
> New `EnsureExistingDirectory` parameter constraint

- datalad_gooey/__init__.py
- datalad_gooey/app.py
- datalad_gooey/askpass.py
- docs/source/index.rst
- setup.cfg
The new `gooey-askpass` command implements the traditional SSH_ASKPASS API. It opens a simple input dialog with the given prompt, collects input, and writes it to `stdout`.
Within Gooey this helper is not the enforced method for anything that honors a normal SSH_ASKPASS setup -- this includes Git and SSH.
So any such requests should now show up in the GUI, rather than be hidden in the terminal.
Closes datalad/datalad-gooey#177
> Simplistic (enforced) ASKPASS helper

- .github/ISSUE_TEMPLATE/issue_template.yml
- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
> Add a very basic help tab

- datalad_gooey/app.py
- datalad_gooey/datalad_ui.py
This is not the epic implementation of datalad core, no units, no 12 progress bars.
There is one progress bar whenever there is any progress reporting ongoing.
If there is more than one process reporting progress at a time, the "average progress" is reported. This makes the progress a bit jumpy.
If a particular progress tracker does not have a known total value (aspirational goal), it is presently ignored. However, the Qt widget allows for "busy indicator" mode. So this could be supported top.
Closes datalad/datalad-gooey#156
https://user-images.githubusercontent.com/136479/191959749-087f2fd3-05ef-4fe0-8264-668927ad60c6.mp4
> Minimal progress reporting in the status bar

- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
Clicking it triggers an internal WTF call, of which the output is automatically enclosed in HTML details tags and markdowns code markup, and copied to the Clipboard. User can then paste it into GitHub issues.
Closes #201
> Add diagnostic infos helper to help tag

- datalad_gooey/param_widgets.py
- datalad_gooey/tests/test_dataladcmd_ui.py
- datalad_gooey/tests/test_param_widget.py
This adds a test for parameter widgets to deliver a representation of the default value (currently `_NoValue`) after initialization with the parameter specification and consequently fixes several classes that failed this test, delivering the native default of the respective Qt widget instead.
It also fixes the Mixin implementation of `get_gooey_param_spec` to deliver the same representation of default under all conditions.
Alternatively, `ChoiceParamWidget` and `PosIntParamWidget` could implement an equivalent of the `StrParamWidget`'s `setModified` approach by wiring up the respective signals, but this simpler approach of just setting the default as the current value also serves the purpose of a visual representation of the default for those widget types. I don't see a case where this …
> Fix defaults for parameter widgets

- datalad_gooey/simplified_api.py
Enhance drop's command config tab with an option to set the `reckless` parameter. This is needed for drop, since otherwise users can't wipe out local datasets w/o no siblings (that may have been created for testing or by accident).
> Allow reckless for drop

- datalad_gooey/param_widgets.py
On a mac it was clipping of the last 3 chars. Now we do 3 chars more than the max length of any item, unless exceeding 80 chars.
Subclasses can call this method too, and also use other parameters.
Closes #229
> Manually adjust choice widget

- datalad_gooey/app.py
Actual error results have been rendered already in this case and the exception's traceback adds nothing useful to the user's perception of the error. Simply remove the hint to the error log in this case.
Closes #217
> Don't alert user to error log on IncompleteResultsError

- docs/source/conf.py
- docs/source/index.rst
Includes links to the datalad docs for the supported commands.
Towards #45
> Docs: add description of supported functionality

- datalad_gooey/param_form_utils.py
- datalad_gooey/param_widgets.py
Provide a TextEdit widget and associate it with the `message` parameter. This widget allows for drag&drop. Furthermore, disabled RichText/HTML for now to keep it simple until this is better tested.
Closes #93
> Multiline text edit widget for message param

- datalad_gooey/fsbrowser.py
For now, simply dump the output of `status --annex=basic` to a file's property tab (if it's part of a dataset. Similarly, just dump `annex info --fast` for a dataset.
Ping #193
> Dump status annex=basic to property tab

- datalad_gooey/api_utils.py
- datalad_gooey/param_form_utils.py
So far we included them "raw" including format macros.
For now we apply the formatting style of the Python API.
Ping https://github.com/datalad/datalad-gooey/issues/265
More will be possible when https://github.com/datalad/datalad/issues/7062 is addressed.
> Format parameter docs properly

- datalad_gooey/api_utils.py
- datalad_gooey/app.py
- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/gooey.py
- datalad_gooey/resources/ui/main_window.ui
The real feat would be an HTML rendering of the docs, but this requires a sphinx-integration.
For now just render a plain-text version and show it.
Closes #270
> Add a "Help" tab and display the command help in it

- datalad_gooey/fsbrowser.py
This should not be necessary, but maybe there are corner cases left, where it is needed, e.g. https://github.com/datalad/datalad-gooey/issues/239, or a user managed to KABOOM the tree population itself.
For now this is the simplest possible implementation (reload the whole thing). Later this could become more clever and more targeted.
Closes #239
> Give user explicit means to refresh the tree browser

- docs/source/gin.rst
Minor fixes to typos and punctuation or flow improvements.
Short explanations for SSH keys and file types.
Section on cloning (no screenshot), replacing todo.
> Polish the Gin walk-through a little

- datalad_gooey/fsbrowser.py
- datalad_gooey/param_multival_widget.py
- datalad_gooey/param_widgets.py
This generalizes the previous implementation, and extends it to `MultiValueInputWidget`. This meta widget will not pass drop events onto an underlying editor widget, if that supports an event.
For unsupported events that comprise of URLs (e.g. `file://` URLs like one would get from a file manager), it passes them on, one-by-one, to the editor, and then builds new items from the editor representation of that URL (e.g. a path).
Drag and drop also works from the FS browser onto any Path input widget, including multi-value input of paths.
Closes #190
Closes #234
https://user-images.githubusercontent.com/136479/193039102-66327c71-6bb8-43ef-8f79-58d5303ee1d4.mp4
> Extend mixin API with helper for drag&drop event handling

- datalad_gooey/constraints.py
- datalad_gooey/param_widgets.py
- datalad_gooey/simplified_api.py
This implements and demos an idea from
https://github.com/datalad/datalad/issues/7054
With this change, a `Constraint` can implement a `for_dataset()` method that return an instance of another constraint (same or different type), tailored for a particular dataset instance.
This feature is demo'ed for `EnsureDatasetSiblingName`, which is `EnsureStr` without a dataset context, but generated an `EnsureChoice` with the names of the siblings of a particular dataset.
`EnsureDatasetSiblingName` is then used in `SiblingChoiceParamWidget`, which enables to move and re-use the sibling discovery to/from the constraint, rather than making the Qt-specific code longer.
> Extend constraint concept to dataset context

- datalad_gooey/param_form_utils.py
Which is for Gooey's purpose equal to `nargs=*`
Closes datalad/datalad-gooey#89
This furthers the usability of
- `create`
- `clone`
- `run`
- `export_archive_ora`
- `foreach_dataset`
- `run_procedure`
in the `gooey-complete` suite.
> Support for `argparse.REMAINDER`

- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
- datalad_gooey/utils.py
It felt inconvenient to need to rescale header (columns) in the tree view each time and/or make window bigger.  I guess there could be more geometries and states to store/restore but this is the main ones I felt need for.
I guess such functionality could become configurable, but as IMHO should be enabled by default for better UX decided to suggest hardcoded first.
> Store/restore "main" geometry/state - window and the file tree header

- datalad_gooey/constraints.py
- datalad_gooey/tests/test_constraints.py
This is a precondition for addressing
https://github.com/datalad/datalad-gooey/issues/284
New versions of -core's `EnsureListOf` and `EnsureTupleOf` are also included. They used to be independent implementations as near-copies. The new implementation merely parameterizes `EnsureIterableOf`.
Ping https://github.com/datalad/datalad/issues/7054
> `EnsureIterableOf` with generator compatibility and length check

- datalad_gooey/constraints.py
- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/param.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/param_multival.py
- datalad_gooey/param_path.py
- datalad_gooey/param_widgets.py
- datalad_gooey/simplified_api.py
- datalad_gooey/tests/test_param_widget.py
Before it was a mess, now it is less of a mess.
Importantly, the parameter widget selection is no longer based on a
mixture of parameter names, constraints, and argparse internal
settings. Now the selection is made solely based on an assigned
`Constraint`.
To make this possible the whole slew of new Constraints that came to
life lately is put to action. The constraint provided by -core's
`Parameter` class is now treated as an "item constraint". This is
turned into a "comprehensive constraint" by wrapping it, as necessary,
into additional constraints. E.g. `nargs='*'` causes
`EnsureIterableOf(list, constraint)`.
A number of other rules are implemented to always yield a single
constraint as a fully qualified ruleset to translate a parameters
requirements into a widget(set).
Importantly, it …
> Rethink parameter widget selection 

- .github/workflows/build_windows_installer.yml
This PR just changes the name of one of the steps of the windows installer build-workflow. This is mainly done to create
a new PR in order to approve the new workflow.
> improve build step name

- .github/workflows/build_windows_installer.yml
This PR modifies the build windows installer-action to always build a windows installer from the latest release of `datalad-gooey`.
This prevents problems with releases and tags that are created for a windows installer that is built from a "random" revision of the code.
> Build windows installer from last release

- .github/workflows/build_windows_installer.yml
This PR re-introduces the ability to select the revision for which a windows installer should be built. In order to minimize complexity and to keep the release history pristine, the resulting artifact will always be uploaded under the latest release (even if the selected revision is older than the release).
> Allow revision selection for installer build

- .github/workflows/build_windows_installer.yml
This PR fixes and error in the windows installer build script. It adds code to determine the upload URL of the latest release through the Web-API. This has become necessary because the action that was used earlier is faulty.
> Fix upload url determination

- datalad_gooey/annex_metadata.py
- datalad_gooey/app.py
- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/flowlayout.py
- datalad_gooey/fsbrowser.py
- datalad_gooey/metadata_editor_base.py
- datalad_gooey/metadata_widget.py
- datalad_gooey/resources/ui/main_window.ui
This brings a new "Metadata" context tab, and an editor widget for git-annex metadata (which can load/save from/to the repo).
Importantly, this is not done in a generic fashion using a CLI implementation, but GUI-native. Main reason is lack of ability of the author.
- Closes #280 
- Closes #266
https://user-images.githubusercontent.com/136479/195285767-7ae675f5-51b9-40cb-8048-f4c67b162404.mp4
TODO
> Metadata editor framework

- datalad_gooey/app.py
- datalad_gooey/fsbrowser.py
- datalad_gooey/history_widget.py
- datalad_gooey/resources/ui/main_window.ui
It shows the (partial) history of whatever is selected (left-click), if there is any history.
The log is loaded on demand so is reasonably fast.
A full commit visualizing dialog is sketched (click on ref), but not implemented yet.
> Add a history tab

- datalad_gooey/fsbrowser.py
This behavior has a number of issues. It stops monitoring that particular directory, but not any of the subdirectories that might also be watched (although equally invisible).
Moreover, re-expanding such an item will put it back on the watch list, but it will not repopulate the item with any changes that occurred in in the meantime.
Overall, this leads to inconsistencies between FS and tree view.
The original intention was to save on resources for watching. However, even on the most limited systems a few dozens are easily possible. I'd say we tune this whenever we actually hit a use case where this is a problem.
Until then, we never stop watch a directory that we started watching once. `QFileSystemWatcher` is already taking care of automatically unwatching directories that get deleted.
- …
> Stop unwatching directories when tree item is collapsed

- datalad_gooey/fsbrowser.py
It passes the path as a local URL to the desktop's "open" handler. This triggers whatever open action a particular desktop configuration considers best.
- Closes datalad/datalad-gooey#332
> Double-clicking on a file in the tree opens it

- datalad_gooey/fsbrowser.py
- datalad_gooey/fsbrowser_item.py
- datalad_gooey/lsdir.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/simplified_api.py
- datalad_gooey/status_light.py
- proper `state` annotation by `lsdir` and `status-light`
- better context handling in dataset actions on absent subdatasets #336 
- allow API command default overrides #219 
- set default recursion limit (for `get`) in simplified API to `1`
- Closes #336 
- Closes #238 
- Closes #219
> Absent subdataset handling

- datalad_gooey/param_form_utils.py
- datalad_gooey/param_multival.py
This is a three part change:
(1) parameters with `nargs=*` or `nargs=+` take a sequence of values. However, datalad is (almost?) universally implemented to also accept a single item in such cases. Internally values are fed to `EnsureList()` rather than exposing this fact as a proper constraint. Here we turn such `nargs` settings in an explicit
`EnsureIterableOf(list, constraint) | constraint`
alternative constrain specification.
(2) The first change makes it necessary to avoid duplicating parameter input widgets in such cases, because `MultiValueWidget` is capable of accepting a single item, making a dedicated single item input for the exact same data type superfluous (and ugly). Here we look for this case when generating input widgets, and we discard the single-item input in favor of the …
> More accurate handling of `nargs=*|+`

- tools/installer_building/build_windows_installer.ps1
- tools/installer_building/resources/run_gooey.ps1
- tools/installer_building/windows-installer-amd64.nsi
This PR modifies the installer in such a way that it contains wheels of `datalad_gooey` and all its requirements, and installs `datalad_gooey` and its requirments from these wheels on the target system. That ensures that `datalad.exe` is working properly on the target system.
In addition `datalaf_gooey` is executed in an environment that contains a PATH entry to the newly installed datalad executable
> Make datalad-command available to datalad_gooey on Windows

- datalad_gooey/credentials.py
For that we need to compare against the stored credential, and set all vanished properties to `None`.
Closes datalad/datalad-gooey#355
> Detect to be deleted credential properties, and delete them

- datalad_gooey/credentials.py
With datalad-next 0.6.2 we also get all half-configured credentials, and undefined credentials that datalad-core could handle.
To avoid confusion these are now labeled in the credential selection combo box of the credential manager.
Because we can deal with secret-less credentials now, we also allow for saving them.
> Label credential as "template" and "no secret"

- datalad_gooey/fsbrowser.py
- datalad_gooey/fsbrowser_item.py
- datalad_gooey/lsdir.py
Until now, symlinks were just labeled as such with no indication of their nature.
This change annotates symlinks, both in terms of `lsdir` results and their representation in the FS tree, with their targets.
While a user still cannot "follow" them within the Gooey, they can at least see what is going on.
Before `status` annotation, also annex'ed files are marked up in this fashion, because I see no need to make an expensive special case for that.
Closes datalad/datalad-gooey#23
Double-click event on a symlink pointing to a directory that is also in the tree view will jump to the respective item as current. If there is no target item yet, it will jump to the closest existing one.
New look:
Behavior with annexed files:
https://user-images.githubusercontent.com/136479/195970884-7e394a36-1402- …
> Annotate symlinks with their targets

- datalad_gooey/askpass.py
This PR fixes #371 
The PR modifies the echo mode of the text entry in `datalad-gooey-askpass`, to "password echo-mode". As a result the entered password is not visible in clear anymore. 
This should be more suitable for demonstrations ;-)
> Use password echo-mode in datalad-gooey-askpass

- datalad_gooey/resource_provider.py
- datalad_gooey/resources/icons/absent.svg
It uses the same geometry as "clean" and all others like it.
For now, it is only used for subdatasets. But if `status-light` would report absent annexed files as such (instead of just `clean`), it would automatically be used for those too.
Closes datalad/datalad-gooey#374
> Icon for absent/downloadable state

- datalad_gooey/app.py
This is taking the approach of @christian-monch from https://github.com/datalad/datalad-gooey/pull/380 and broadening its impact to any means of installing datalad-gooey on windows.
Closes datalad/datalad-gooey#371
> Prevent terminal interaction on windows

- datalad_gooey/param_path.py
- datalad_gooey/param_widgets.py
- datalad_gooey/utils.py
This eases the specification, e.g., clone source and destination.
> Equip `StrParameter`'s line edit to accept path drops from FSBrowser

- datalad_gooey/fsbrowser.py
The cache was not invalidated properly, leading to deleted items beeing handed out. This is behind a whole range of ill behavior (likely).
Re-assessing the performance impact of caching, I found it to be neglible. Hence I disabled it with a comment, instead of implementing cache invalidation (which is fairly doable, but seems not useful).
Closes datalad/datalad-gooey#400
Closes datalad/datalad-gooey#399
Closes datalad/datalad-gooey#398
Closes datalad/datalad-gooey#397
Closes datalad/datalad-gooey#396
Closes datalad/datalad-gooey#395
Closes datalad/datalad-gooey#387
Closes datalad/datalad-gooey#379
> Stop caching `FSBrowserItem._get_item_from_path()`

- docs/source/getting-started.rst
- docs/source/installation.rst
This updates the documentation for:
- update the link to the windows installer after it has been moved to the main gooey repo (now: datalad/datalad-gooey/releases)
- list Terminal as the way to launch Gooey on MacOS, replacing Applications (we don't have Applications entry)
> DOC: fix instructions

- docs/source/conf.py
The "old" format of intersphinx_mapping is deprecated since Sphinx 6.2 and started causing warnings treated as errors in the doc build GitHub action (but not Read The Docs, as it currently uses Sphinx v5.3.0) in #428 
This PR removes the use of `intersphinx` extension and `intersphinx_mapping` config option, as it was an unused placeholder from the extension template (see similar removal in https://github.com/datalad/datalad-next/commit/a1f3af9f4e82f9b4ded9aa4cbcc2df8e3c0f1976).
This PR can be made less invasive by reverting the last commit and keeping `intersphinx` with an updated `intersphinx_mapping`.
For reference: 
https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html
> Doc build: update intersphinx_mapping

- readthedocs.yml
> Add readthedocs configuration from extension template

- datalad_gooey/constraints.py
- datalad_gooey/credentials.py
- datalad_gooey/gooey.py
- datalad_gooey/lsdir.py
- datalad_gooey/status_light.py
Changes imports of `CredentialManager` (from next) and `eval_results` to match their current locations. Closes #427
> Adjust imports deprecated in next 1.0.0 and core 0.18
