datalad/datalad-gooey

- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
PR makes changes to:
- `main_window.ui`: adds pushbutton
- `app.py` connects button clicked signal to text clear slot
Closes #37
> NF: adds a pushbutton to clear the log text

- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/param_widgets.py
- datalad_gooey/resources/ui/cmdparam_widget.ui
> ENH: add command name to command config ui

- datalad_gooey/param_form_utils.py
This is limited (for now) to `on_failure` and `result_renderer` as the other ones don't seem to make sense in the GUI at this point. Eventually `return_type` may become relevant as well.
This also comes with a slight change to the parameter widget helpers: Passing down `Parameter` instances instead of the command class, since this is the only thing the command class was used for and this enables reuse of the helpers outside the context of a specific command. Also: `allargs` was declared to possibly be None by an intermediate helper, who would then pass it down to another one where `allargs` was mandatory. Allow for `None` all the way now.
Ping #16
> Add common opts to command tab

- datalad_gooey/app.py
- datalad_gooey/dataladcmd_exec.py
Closes https://github.com/datalad/datalad-gooey/issues/26
> Better user feedback re ongoing command executions

- datalad_gooey/fsbrowser.py
This is not yet the big thing.
> Smaller performance tune-up of status annotation

- .github/config.yml
- .github/workflows/update-contributors.yml
> Add a tributors workflow to recognize contributors and also say hi

- datalad_gooey/simplified_api.py
For simple getting or dropping a single file, add get & drop to file command list.
> Adding Get & Drop for file commands

- datalad_gooey/fsbrowser_item.py
Closes https://github.com/datalad/datalad-gooey/issues/149
> Fix type annotation of files

- datalad_gooey/app.py
- datalad_gooey/datalad_ui.py
- datalad_gooey/dataladcmd_exec.py
- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/fsbrowser.py
- datalad_gooey/param_widgets.py
> Stop emitting mutable dicts via signals

- datalad_gooey/param_form_utils.py
- datalad_gooey/param_widgets.py
Closes datalad/datalad-gooey#92
> Dedicated cfg_proc parameter input widget

- datalad_gooey/app.py
Closes datalad/datalad-gooey#161
> Also record command failure in command log

- datalad_gooey/param_widgets.py
https://github.com/datalad/datalad-gooey/issues/114
> Blind attempt to address file dialog crash

- datalad_gooey/app.py
Users can not be expected to have a terminal (visible). Any interaction attempt would seemingly hang the app.
This changes turn any such event into a crash/error.
Providing GUI-based alternatives for interaction is still necessary, but an orthogonal effort
Ping datalad/datalad-gooey#177
Closes datalad/datalad-gooey#176
> Prevent Git terminal interaction throughout the entire app

- datalad_gooey/app.py
But keep them as status bar messages, and also report their crashes in the error log, still.
Closes datalad/datalad-gooey#182
> Exclude internal helper calls from command log

- datalad_gooey/param_widgets.py
Closes datalad/datalad-gooey#185
> Do not drag a `cfg_` prefix along for configu procedures

- datalad_gooey/simplified_api.py
Here's a proposal for a simpler API for ``create-sibling-github`` and ``create-sibling-gin`:
> Draft simplistic parameter and parameter order for create sibling github/gin

- datalad_gooey/tests/test_lsdir.py
This PR adds a few tests for `lsdir.py`. I would appreciate a good review, since this is the first time I've used mock patching.
In partial fulfilment of #48
> Add tests for `lsdir`

- datalad_gooey/gooey.py
- datalad_gooey/postinstall.py
- datalad_gooey/resource_provider.py
- setup.cfg
We already have a resource provider mechanism. So let's use this for the desktop file too.
> Avoid importlib

- datalad_gooey/datalad_ui.py
- datalad_gooey/dataladcmd_ui.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/param_multival_widget.py
- datalad_gooey/param_widgets.py
- datalad_gooey/tests/test_param_widget.py
- Closes #212 
- Closes #210 
- Closes #181
> Loads of changes re parameter widgets

- datalad_gooey/param_widgets.py
I can now click on files or directories in my native OS's file browser, and drag them into the path editors of the parameter widget. It only works for single files. Screenrecording below for illustration.
[Screencast from 09-27-2022 10:46:00 AM.webm](https://user-images.githubusercontent.com/29738718/192479038-d441b43f-2c9c-4063-b478-b88ff506ca86.webm)
> Drag and Drop Support

- docs/source/index.rst
- docs/source/installation.rst
> DOC: add installation instructions

- docs/source/getting-started.rst
- docs/source/gin.rst
- docs/source/index.rst
- docs/source/installation.rst
Also creates a "Getting started page"
> Start drafting user guide with gin example

- docs/source/cmdline.rst
- docs/source/datalad-concepts.rst
- docs/source/getting-started.rst
- docs/source/index.rst
- docs/source/modref.rst
> More work on the Docs

- datalad_gooey/app.py
- datalad_gooey/credentials.py
- datalad_gooey/param_widgets.py
- datalad_gooey/resources/ui/credentials_dialog.ui
- datalad_gooey/resources/ui/main_window.ui
- datalad_gooey/utility_actions.py
It is based on the credential management from datalad-next.
It can query, set, and delete credentials
Ping datalad/datalad-next#81
Closes #99
> Credential management dialog

- datalad_gooey/app.py
- datalad_gooey/resources/ui/main_window.ui
- datalad_gooey/resources/ui/user_dialog.ui
- datalad_gooey/utility_actions.py
sense to support this with a simple dialog that gathers the essentials.
Closes #147
> Support setting Git identity, and auto-launch if unset

- datalad_gooey/constraints.py
- datalad_gooey/param_alt_widget.py
- datalad_gooey/param_form_utils.py
- datalad_gooey/param_mixin.py
- datalad_gooey/param_multival_widget.py
- datalad_gooey/param_path_widget.py
- datalad_gooey/param_widgets.py
- datalad_gooey/simplified_api.py
- datalad_gooey/tests/test_param_widget.py
Replaces https://github.com/datalad/datalad-gooey/pull/135
This became a monster PR, because of the dire situation the validator use was in before.
It is not perfect now, but better. See the commit messages for a winding storyline.
Closes datalad/datalad-gooey#61
Closes datalad/datalad-gooey#90
> `AlternativeParamWidget` for parameters with `AltConstraints`

- datalad_gooey/constraints.py
(partial) fix for #360. ping @bpoldrack
> If new credential entry is allowed, don't constrain to existing creds

- datalad_gooey/constraints.py
Need not know git annex special remote info.
- Closes datalad/datalad-gooey#365
- Closes datalad/datalad-gooey#342
> Speed up sibling name constraint

- datalad_gooey/app.py
- datalad_gooey/fsbrowser.py
It will open whatever file manager is default on a system
Closes #352
> Support "open in filemanager" context menu action

- datalad_gooey/param_widgets.py
Closes datalad/datalad-gooey#378
> Ensure choices in combobox are sorted and NoValue selects '--none--'

- datalad_gooey/constraints.py
- datalad_gooey/credentials.py
- setup.cfg
In anticipation of a coming proper ``datalad-next`` 1.0.0 release, to address #416
> Adjustments for datalad-next 1.0.0

- .appveyor.yml
> Update Macos build images to monterey to fix CI installation failures
